stages:
  - build

variables:
  IMAGE_TAG: $CI_COMMIT_REF_NAME-$CI_PIPELINE_ID

docker-build:
  stage: build
  tags:
    - k8s-runner-2
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$IMAGE_TAG" .
    - docker push "$CI_REGISTRY_IMAGE:$IMAGE_TAG"
  after_script:
    - docker tag "$CI_REGISTRY_IMAGE:$IMAGE_TAG" $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:latest